//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class postgresEntities : DbContext
    {
        public postgresEntities()
            : base("name=postgresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apertura_caja> apertura_caja { get; set; }
        public virtual DbSet<cierre_caja> cierre_caja { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<compaÑia> compaÑia { get; set; }
        public virtual DbSet<cont_venta> cont_venta { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<medicamento> medicamento { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<rol_empleado> rol_empleado { get; set; }
        public virtual DbSet<suc_medicamento> suc_medicamento { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<venta> venta { get; set; }
    }
}
