//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class suc_medicamento
    {
        public string eanmedicamento { get; set; }
        public int idsucursal { get; set; }
        public int cantidad { get; set; }
        public int activo { get; set; }
    
        public virtual medicamento medicamento { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
