//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class apertura_caja
    {
        public apertura_caja()
        {
            this.cierre_caja = new HashSet<cierre_caja>();
        }
    
        public int id { get; set; }
        public int numcaja { get; set; }
        public Nullable<int> cedcajero { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> dinero { get; set; }
        public string activo { get; set; }
    
        public virtual ICollection<cierre_caja> cierre_caja { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
