//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class postgresEntities : DbContext
    {
        public postgresEntities()
            : base("name=postgresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<apertura_caja> apertura_caja { get; set; }
        public DbSet<cierre_caja> cierre_caja { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<compaÃ_ia> compaÃ_ia { get; set; }
        public DbSet<cont_venta> cont_venta { get; set; }
        public DbSet<empleado> empleado { get; set; }
        public DbSet<medicamento> medicamento { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<rol_empleado> rol_empleado { get; set; }
        public DbSet<suc_medicamento> suc_medicamento { get; set; }
        public DbSet<sucursal> sucursal { get; set; }
        public DbSet<test> test { get; set; }
        public DbSet<venta> venta { get; set; }
    }
}
