//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicamento
    {
        public medicamento()
        {
            this.cont_venta = new HashSet<cont_venta>();
            this.suc_medicamento = new HashSet<suc_medicamento>();
        }
    
        public string ean { get; set; }
        public string casafarmaceutica { get; set; }
        public string prescripcion { get; set; }
        public string cantidadtotal { get; set; }
        public string activo { get; set; }
    
        public virtual ICollection<cont_venta> cont_venta { get; set; }
        public virtual ICollection<suc_medicamento> suc_medicamento { get; set; }
    }
}
