//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class suc_medicamento
    {
        public int id { get; set; }
        public string eanmedicamento { get; set; }
        public Nullable<int> idsucursal { get; set; }
        public int cantidad { get; set; }
        public string activo { get; set; }
    
        public virtual medicamento medicamento { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
