//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal
    {
        public sucursal()
        {
            this.empleado1 = new HashSet<empleado>();
            this.suc_medicamento = new HashSet<suc_medicamento>();
        }
    
        public int id { get; set; }
        public Nullable<int> cedadmin { get; set; }
        public Nullable<int> idcompaÃ_ia { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string provincia { get; set; }
        public string canton { get; set; }
        public string distrito { get; set; }
        public string indicaciones { get; set; }
        public string activo { get; set; }
    
        public virtual compaÃ_ia compaÃ_ia { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual ICollection<empleado> empleado1 { get; set; }
        public virtual ICollection<suc_medicamento> suc_medicamento { get; set; }
    }
}
