//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public venta()
        {
            this.cont_venta = new HashSet<cont_venta>();
        }
    
        public int id { get; set; }
        public int numcaja { get; set; }
        public Nullable<int> cedcliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipopago { get; set; }
        public string activo { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<cont_venta> cont_venta { get; set; }
    }
}
